# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "private_network", ip: "192.168.56.15"

  config.ssh.forward_agent = true

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ops.pub").first.strip
    s.inline = <<-SHELL
      # echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      # echo #{ssh_pub_key} >> /root/.ssh/authorized_keys

      sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      sudo systemctl restart sshd

      # change vagrant user to require sudo password
      sudo sed -i 's/vagrant ALL=(ALL) NOPASSWD:ALL/vagrant ALL=(ALL:ALL) ALL/g' /etc/sudoers.d/vagrant

      # sudo sh -c 'echo root:foo | chpasswd'
    SHELL
  end
end
